site_name: LCSC Learning Hub
site_url: https://docs.letzpwn.lu
repo_url: https://github.com/LetzPwn/lcsc-mkdocs
theme:
  name: material
plugins:
    - awesome-pages
    - search
nav:
    - Start here: index.md
    - Cryptography:
        - cryptography/introduction.md
        - cryptography/ressources.md
    - Web Security:
        - web-security/introduction.md
        - web-security/ressources.md
    - Reverse Engineering:
        - reverse-engineering/introduction.md
        - "A first challenge: The Oracle's Whimsy": reverse-engineering/a-first-challenge.md
        - reverse-engineering/ressources.md
    - Pwn:
        - pwn/introduction.md     
    #- Digital Forensics:
    #    - digital-forensics/introduction.md
    #- Binary Exploitation:
    #    - binary-exploitation/introduction.md
    #- Network Analysis:
    #    - network-analysis/introduction.md
    #- OSINT:
    #    - osint/introduction.md
    #- Hardware Security:
    #    - hardware-security/introduction.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    
    
   
